# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: examples
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - image: kelseyhightower/helloworld:v2
          imagePullPolicy: Always
          name: helloworld
          ports:
            - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: examples
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: helloworld
---
# TLS Setup for App
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: examples
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - $LB_HOST
    secretName: hello-world-tls
  rules:
  - host: $LB_HOST
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld
            port:
              number: 80